spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chaos_platform?useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
    consumer:
      group-id: chaos-platform
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      
chaosblade:
  install:
    path: /opt/chaosblade
    timeout: 300  # 安装超时时间（秒）
  version: 1.7.0  # ChaosBlade 版本

logging:
  level:
    com.chaos.platform: DEBUG

jwt:
  secret: your-secret-key-here
  expiration: 86400000  # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: chaos-platform
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always