spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chaos_platform?useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chaos-platform-dev

logging:
  level:
    com.chaos.platform: DEBUG
    org.springframework: INFO 