spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/chaos_platform?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: chaos-platform

logging:
  level:
    root: WARN
    com.chaos.platform: INFO 